---
driver:
  name: ec2
  security_group_ids: ["sg-865fb1e2"]
  region: us-east-1
  subnet_id: subnet-a4638e98
  instance_type: m3.medium
  spot_price: 0.01

transport:
 ssh_key: ~/.ssh/<%= ENV['USER'] %>

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[chef-ampache::default]
    attributes:
