name 'chef-ampache'
maintainer 'Arunderwood'
maintainer_email 'you@example.com'
license 'all_rights'
source_url 'https://github.com/arunderwood/chef-ampache'
issues_url 'https://github.com/arunderwood/chef-ampache/issues'
description 'Installs/Configures chef-ampache'
long_description 'Installs/Configures chef-ampache'
version '0.1.0'

depends 'apache2', '~> 3.2'
